name: rego-test
on:
  push:
    branches:
      - development

env:
  GCP_PROJECT: ${{secrets.GCP_PROJECT}}
  ZONE: us.gcr.io
  IMAGE: open-policy-agent
  VERSION: 0.20.4
  SA_JSON_KEY: ${{ secrets.SA_JSON_KEY }}

jobs:
  rego-test:
    runs-on: ubuntu-latest
    steps: 
      - name: GCR login
        run: |-
          echo $SA_JSON_KEY | docker login -u _json_key --password-stdin https://$ZONE

    container: 
      image: $ZONE/$GCP_PROJECT/$IMAGE:$VERSION
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: opa version
        run: opa version

      - name: rego-test
        run: |-
          ls -l
          opa test . -v